# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a7477ee1cbe764facb67f75c46f5a25b5422e95e837dc2fbaf0a77ad68ccb603f10e889740a409c5d42786640fdacf025c743a19178f421838d1526bfbeaa2c

test:
  secret_key_base: e8e1c829eee4c0a378378560df3c179fde23393223eb866ec41ef61ca31dcb352dd3c8fba283e957f7a6b3576463a6e2be6f671cd9285d0311b1e83080ee2dd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
